[package]
name = "outcome-markets"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(target_os, values("solana"))',
    'cfg(feature, values("anchor-debug", "custom-heap", "custom-panic"))',
] }

[lib]
crate-type = ["cdylib", "lib"]
name = "outcome_markets"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]


[dependencies]
anchor-lang = "=0.31.1"
anchor-spl = { version = "=0.31.1", features = ["metadata"] }
pyth-solana-receiver-sdk = "=1.0.1"
pythnet-sdk = "=2.3.1"
solana-security-txt = "1.1.2"
default-env = "0.1.1"

[dev-dependencies]
assert_matches = "=1.5.0"
base64 = "=0.22.1"
litesvm = "=0.8.0"
serde_json = "=1.0.145"
solana-account = "=3.0.0"
solana-clock = "=3.0.1"
solana-keypair = "=3.0.1"
solana-message = "=3.0.1"
solana-pubkey = "=3.0.0"
solana-sdk = "=2.3.0"
solana-transaction = "=3.0.1"
spl-token = { version = "=8.0.0", default-features = false, features = ["no-entrypoint"] }
